/* Generated By:JavaCC: Do not edit this line. TraductorConstants.java */
package traductor;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface TraductorConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int letra = 6;
  /** RegularExpression Id. */
  int digpos = 7;
  /** RegularExpression Id. */
  int dig = 8;
  /** RegularExpression Id. */
  int dec = 9;
  /** RegularExpression Id. */
  int exp = 10;
  /** RegularExpression Id. */
  int litNat = 11;
  /** RegularExpression Id. */
  int litReal = 12;
  /** RegularExpression Id. */
  int pyc = 13;
  /** RegularExpression Id. */
  int tInt = 14;
  /** RegularExpression Id. */
  int tReal = 15;
  /** RegularExpression Id. */
  int opAsig = 16;
  /** RegularExpression Id. */
  int opIgual = 17;
  /** RegularExpression Id. */
  int opMenor = 18;
  /** RegularExpression Id. */
  int opMayor = 19;
  /** RegularExpression Id. */
  int opMenIg = 20;
  /** RegularExpression Id. */
  int opMayIg = 21;
  /** RegularExpression Id. */
  int opDistinto = 22;
  /** RegularExpression Id. */
  int opIn = 23;
  /** RegularExpression Id. */
  int opOut = 24;
  /** RegularExpression Id. */
  int opMenos = 25;
  /** RegularExpression Id. */
  int opNot = 26;
  /** RegularExpression Id. */
  int opAnd = 27;
  /** RegularExpression Id. */
  int opOr = 28;
  /** RegularExpression Id. */
  int opMult = 29;
  /** RegularExpression Id. */
  int opDiv = 30;
  /** RegularExpression Id. */
  int opMod = 31;
  /** RegularExpression Id. */
  int opSuma = 32;
  /** RegularExpression Id. */
  int opCastInt = 33;
  /** RegularExpression Id. */
  int opCastReal = 34;
  /** RegularExpression Id. */
  int pa = 35;
  /** RegularExpression Id. */
  int pc = 36;
  /** RegularExpression Id. */
  int id = 37;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<token of kind 5>",
    "<letra>",
    "<digpos>",
    "<dig>",
    "<dec>",
    "<exp>",
    "<litNat>",
    "<litReal>",
    "\";\"",
    "\"int\"",
    "\"real\"",
    "\"=\"",
    "\"==\"",
    "\"<\"",
    "\">\"",
    "\"<=\"",
    "\">=\"",
    "\"!=\"",
    "\"in\"",
    "\"out\"",
    "\"-\"",
    "\"!\"",
    "\"&&\"",
    "\"||\"",
    "\"*\"",
    "\"/\"",
    "\"%\"",
    "\"+\"",
    "\"(int)\"",
    "\"(real)\"",
    "\"(\"",
    "\")\"",
    "<id>",
  };

}
